# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "Blog Cyber"
name = "Blog Cyber"
url = "https://jaybird1291.github.io/blog/"
weight = 1
newtab = true

[social.params]
icon = "shield"
